// automatically generated by the FlatBuffers compiler, do not modify

package frc.taurus.config;

public final class ChannelType {
  private ChannelType() { }
  public static final int JoystickStatus = 0;
  public static final int JoystickGoal = 1;
  public static final int TestMessage = 2;
  public static final int TestMessage2 = 3;

  public static final String[] names = { "JoystickStatus", "JoystickGoal", "TestMessage", "TestMessage2", };

  public static String name(int e) { return names[e]; }
}

