// automatically generated by the FlatBuffers compiler, do not modify

package frc.taurus.messages;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class JoystickStatus extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static JoystickStatus getRootAsJoystickStatus(ByteBuffer _bb) { return getRootAsJoystickStatus(_bb, new JoystickStatus()); }
  public static JoystickStatus getRootAsJoystickStatus(ByteBuffer _bb, JoystickStatus obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public JoystickStatus __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double timestamp() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public float axis0() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float axis1() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float axis2() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float axis3() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float axis4() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float axis5() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public boolean button1() { int o = __offset(18); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button2() { int o = __offset(20); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button3() { int o = __offset(22); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button4() { int o = __offset(24); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button5() { int o = __offset(26); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button6() { int o = __offset(28); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button7() { int o = __offset(30); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button8() { int o = __offset(32); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button9() { int o = __offset(34); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button10() { int o = __offset(36); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button11() { int o = __offset(38); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button12() { int o = __offset(40); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button13() { int o = __offset(42); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button14() { int o = __offset(44); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button15() { int o = __offset(46); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean button16() { int o = __offset(48); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int pov() { int o = __offset(50); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createJoystickStatus(FlatBufferBuilder builder,
      double timestamp,
      float axis0,
      float axis1,
      float axis2,
      float axis3,
      float axis4,
      float axis5,
      boolean button1,
      boolean button2,
      boolean button3,
      boolean button4,
      boolean button5,
      boolean button6,
      boolean button7,
      boolean button8,
      boolean button9,
      boolean button10,
      boolean button11,
      boolean button12,
      boolean button13,
      boolean button14,
      boolean button15,
      boolean button16,
      int pov) {
    builder.startTable(24);
    JoystickStatus.addTimestamp(builder, timestamp);
    JoystickStatus.addPov(builder, pov);
    JoystickStatus.addAxis5(builder, axis5);
    JoystickStatus.addAxis4(builder, axis4);
    JoystickStatus.addAxis3(builder, axis3);
    JoystickStatus.addAxis2(builder, axis2);
    JoystickStatus.addAxis1(builder, axis1);
    JoystickStatus.addAxis0(builder, axis0);
    JoystickStatus.addButton16(builder, button16);
    JoystickStatus.addButton15(builder, button15);
    JoystickStatus.addButton14(builder, button14);
    JoystickStatus.addButton13(builder, button13);
    JoystickStatus.addButton12(builder, button12);
    JoystickStatus.addButton11(builder, button11);
    JoystickStatus.addButton10(builder, button10);
    JoystickStatus.addButton9(builder, button9);
    JoystickStatus.addButton8(builder, button8);
    JoystickStatus.addButton7(builder, button7);
    JoystickStatus.addButton6(builder, button6);
    JoystickStatus.addButton5(builder, button5);
    JoystickStatus.addButton4(builder, button4);
    JoystickStatus.addButton3(builder, button3);
    JoystickStatus.addButton2(builder, button2);
    JoystickStatus.addButton1(builder, button1);
    return JoystickStatus.endJoystickStatus(builder);
  }

  public static void startJoystickStatus(FlatBufferBuilder builder) { builder.startTable(24); }
  public static void addTimestamp(FlatBufferBuilder builder, double timestamp) { builder.addDouble(0, timestamp, 0.0); }
  public static void addAxis0(FlatBufferBuilder builder, float axis0) { builder.addFloat(1, axis0, 0.0f); }
  public static void addAxis1(FlatBufferBuilder builder, float axis1) { builder.addFloat(2, axis1, 0.0f); }
  public static void addAxis2(FlatBufferBuilder builder, float axis2) { builder.addFloat(3, axis2, 0.0f); }
  public static void addAxis3(FlatBufferBuilder builder, float axis3) { builder.addFloat(4, axis3, 0.0f); }
  public static void addAxis4(FlatBufferBuilder builder, float axis4) { builder.addFloat(5, axis4, 0.0f); }
  public static void addAxis5(FlatBufferBuilder builder, float axis5) { builder.addFloat(6, axis5, 0.0f); }
  public static void addButton1(FlatBufferBuilder builder, boolean button1) { builder.addBoolean(7, button1, false); }
  public static void addButton2(FlatBufferBuilder builder, boolean button2) { builder.addBoolean(8, button2, false); }
  public static void addButton3(FlatBufferBuilder builder, boolean button3) { builder.addBoolean(9, button3, false); }
  public static void addButton4(FlatBufferBuilder builder, boolean button4) { builder.addBoolean(10, button4, false); }
  public static void addButton5(FlatBufferBuilder builder, boolean button5) { builder.addBoolean(11, button5, false); }
  public static void addButton6(FlatBufferBuilder builder, boolean button6) { builder.addBoolean(12, button6, false); }
  public static void addButton7(FlatBufferBuilder builder, boolean button7) { builder.addBoolean(13, button7, false); }
  public static void addButton8(FlatBufferBuilder builder, boolean button8) { builder.addBoolean(14, button8, false); }
  public static void addButton9(FlatBufferBuilder builder, boolean button9) { builder.addBoolean(15, button9, false); }
  public static void addButton10(FlatBufferBuilder builder, boolean button10) { builder.addBoolean(16, button10, false); }
  public static void addButton11(FlatBufferBuilder builder, boolean button11) { builder.addBoolean(17, button11, false); }
  public static void addButton12(FlatBufferBuilder builder, boolean button12) { builder.addBoolean(18, button12, false); }
  public static void addButton13(FlatBufferBuilder builder, boolean button13) { builder.addBoolean(19, button13, false); }
  public static void addButton14(FlatBufferBuilder builder, boolean button14) { builder.addBoolean(20, button14, false); }
  public static void addButton15(FlatBufferBuilder builder, boolean button15) { builder.addBoolean(21, button15, false); }
  public static void addButton16(FlatBufferBuilder builder, boolean button16) { builder.addBoolean(22, button16, false); }
  public static void addPov(FlatBufferBuilder builder, int pov) { builder.addInt(23, pov, 0); }
  public static int endJoystickStatus(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishJoystickStatusBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedJoystickStatusBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public JoystickStatus get(int j) { return get(new JoystickStatus(), j); }
    public JoystickStatus get(JoystickStatus obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

